%YAML:1.0

# MODIFIED    
# Undead Reckoning
# Date: 01/21/26
# By: Quinn Levinson

#lrf parameters       The more accurate parameters you provide, the better performance
laser_enable: true
laser_topic: "/scan"
laser_frame: "laser_link"

lrf_to_camera_rotation: [ 1, 0, 0,
                           0, 1, 0,
                           0, 0, 1 ]

lrf_to_camera_translation: [ 0, 0, 0 ]

sampling_rate: 100 # must be between 5 Hz and 1000 Hz
laser_noise_std: 0.01     # m
laser_resolution: 0.0001 # m
laser_downsample: 1
#laser_min_range: 0.05 # m increased to 5m to remove outliers from lighting interference
laser_min_range: 4 # m
laser_max_range: 50.0 # m

# END MODIFIED